// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.testappnongpdownload.app.playstoreapiutils;

@SuppressWarnings("hiding")
public interface GoogleServicesFramework {

  public static final class LoginRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LoginRequest[] _emptyArray;
    public static LoginRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LoginRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string packetid = 1;
    public String packetid;

    // optional string domain = 2;
    public String domain;

    // optional string user = 3;
    public String user;

    // optional string resource = 4;
    public String resource;

    // optional string token = 5;
    public String token;

    // optional string deviceid = 6;
    public String deviceid;

    // optional int64 lastrmqid = 7;
    public long lastrmqid;

    // repeated .Setting settings = 8;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[] settings;

    // optional int32 compress = 9;
    public int compress;

    // repeated string persistentids = 10;
    public String[] persistentids;

    // optional bool includestreamidinprotobuf = 11;
    public boolean includestreamidinprotobuf;

    // optional bool adaptiveheartbeat = 12;
    public boolean adaptiveheartbeat;

    // optional .HeartBeatStat heartbeatstat = 13;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.HeartBeatStat heartbeatstat;

    // optional bool usermq2 = 14;
    public boolean usermq2;

    // optional int64 accountid = 15;
    public long accountid;

    // optional int64 unknown1 = 16;
    public long unknown1;

    // optional int32 networktype = 17;
    public int networktype;

    public LoginRequest() {
      clear();
    }

    public LoginRequest clear() {
      packetid = "";
      domain = "";
      user = "";
      resource = "";
      token = "";
      deviceid = "";
      lastrmqid = 0L;
      settings = com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting.emptyArray();
      compress = 0;
      persistentids = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      includestreamidinprotobuf = false;
      adaptiveheartbeat = false;
      heartbeatstat = null;
      usermq2 = false;
      accountid = 0L;
      unknown1 = 0L;
      networktype = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packetid.equals("")) {
        output.writeString(1, this.packetid);
      }
      if (!this.domain.equals("")) {
        output.writeString(2, this.domain);
      }
      if (!this.user.equals("")) {
        output.writeString(3, this.user);
      }
      if (!this.resource.equals("")) {
        output.writeString(4, this.resource);
      }
      if (!this.token.equals("")) {
        output.writeString(5, this.token);
      }
      if (!this.deviceid.equals("")) {
        output.writeString(6, this.deviceid);
      }
      if (this.lastrmqid != 0L) {
        output.writeInt64(7, this.lastrmqid);
      }
      if (this.settings != null && this.settings.length > 0) {
        for (int i = 0; i < this.settings.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting element = this.settings[i];
          if (element != null) {
            output.writeMessage(8, element);
          }
        }
      }
      if (this.compress != 0) {
        output.writeInt32(9, this.compress);
      }
      if (this.persistentids != null && this.persistentids.length > 0) {
        for (int i = 0; i < this.persistentids.length; i++) {
          String element = this.persistentids[i];
          if (element != null) {
            output.writeString(10, element);
          }
        }
      }
      if (this.includestreamidinprotobuf != false) {
        output.writeBool(11, this.includestreamidinprotobuf);
      }
      if (this.adaptiveheartbeat != false) {
        output.writeBool(12, this.adaptiveheartbeat);
      }
      if (this.heartbeatstat != null) {
        output.writeMessage(13, this.heartbeatstat);
      }
      if (this.usermq2 != false) {
        output.writeBool(14, this.usermq2);
      }
      if (this.accountid != 0L) {
        output.writeInt64(15, this.accountid);
      }
      if (this.unknown1 != 0L) {
        output.writeInt64(16, this.unknown1);
      }
      if (this.networktype != 0) {
        output.writeInt32(17, this.networktype);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packetid);
      }
      if (!this.domain.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domain);
      }
      if (!this.user.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.user);
      }
      if (!this.resource.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.resource);
      }
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.token);
      }
      if (!this.deviceid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.deviceid);
      }
      if (this.lastrmqid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(7, this.lastrmqid);
      }
      if (this.settings != null && this.settings.length > 0) {
        for (int i = 0; i < this.settings.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting element = this.settings[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(8, element);
          }
        }
      }
      if (this.compress != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.compress);
      }
      if (this.persistentids != null && this.persistentids.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.persistentids.length; i++) {
          String element = this.persistentids[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.includestreamidinprotobuf != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(11, this.includestreamidinprotobuf);
      }
      if (this.adaptiveheartbeat != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(12, this.adaptiveheartbeat);
      }
      if (this.heartbeatstat != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(13, this.heartbeatstat);
      }
      if (this.usermq2 != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(14, this.usermq2);
      }
      if (this.accountid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(15, this.accountid);
      }
      if (this.unknown1 != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(16, this.unknown1);
      }
      if (this.networktype != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(17, this.networktype);
      }
      return size;
    }

    @Override
    public LoginRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packetid = input.readString();
            break;
          }
          case 18: {
            this.domain = input.readString();
            break;
          }
          case 26: {
            this.user = input.readString();
            break;
          }
          case 34: {
            this.resource = input.readString();
            break;
          }
          case 42: {
            this.token = input.readString();
            break;
          }
          case 50: {
            this.deviceid = input.readString();
            break;
          }
          case 56: {
            this.lastrmqid = input.readInt64();
            break;
          }
          case 66: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 66);
            int i = this.settings == null ? 0 : this.settings.length;
              com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[] newArray =
                new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.settings, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting();
            input.readMessage(newArray[i]);
            this.settings = newArray;
            break;
          }
          case 72: {
            this.compress = input.readInt32();
            break;
          }
          case 82: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 82);
            int i = this.persistentids == null ? 0 : this.persistentids.length;
            String[] newArray = new String[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.persistentids, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.persistentids = newArray;
            break;
          }
          case 88: {
            this.includestreamidinprotobuf = input.readBool();
            break;
          }
          case 96: {
            this.adaptiveheartbeat = input.readBool();
            break;
          }
          case 106: {
            if (this.heartbeatstat == null) {
              this.heartbeatstat = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.HeartBeatStat();
            }
            input.readMessage(this.heartbeatstat);
            break;
          }
          case 112: {
            this.usermq2 = input.readBool();
            break;
          }
          case 120: {
            this.accountid = input.readInt64();
            break;
          }
          case 128: {
            this.unknown1 = input.readInt64();
            break;
          }
          case 136: {
            this.networktype = input.readInt32();
            break;
          }
        }
      }
    }

    public static LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LoginRequest(), data);
    }

    public static LoginRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LoginRequest().mergeFrom(input);
    }
  }

  public static final class HeartBeatStat extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HeartBeatStat[] _emptyArray;
    public static HeartBeatStat[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HeartBeatStat[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string ip = 1;
    public String ip;

    // optional bool timeout = 2;
    public boolean timeout;

    // optional int64 interval = 3;
    public long interval;

    public HeartBeatStat() {
      clear();
    }

    public HeartBeatStat clear() {
      ip = "";
      timeout = false;
      interval = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.ip.equals("")) {
        output.writeString(1, this.ip);
      }
      if (this.timeout != false) {
        output.writeBool(2, this.timeout);
      }
      if (this.interval != 0L) {
        output.writeInt64(3, this.interval);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.ip.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.ip);
      }
      if (this.timeout != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.timeout);
      }
      if (this.interval != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.interval);
      }
      return size;
    }

    @Override
    public HeartBeatStat mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.ip = input.readString();
            break;
          }
          case 16: {
            this.timeout = input.readBool();
            break;
          }
          case 24: {
            this.interval = input.readInt64();
            break;
          }
        }
      }
    }

    public static HeartBeatStat parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HeartBeatStat(), data);
    }

    public static HeartBeatStat parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HeartBeatStat().mergeFrom(input);
    }
  }

  public static final class Setting extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Setting[] _emptyArray;
    public static Setting[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Setting[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string key = 1;
    public String key;

    // optional string value = 2;
    public String value;

    public Setting() {
      clear();
    }

    public Setting clear() {
      key = "";
      value = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.key.equals("")) {
        output.writeString(1, this.key);
      }
      if (!this.value.equals("")) {
        output.writeString(2, this.value);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.key.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.key);
      }
      if (!this.value.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.value);
      }
      return size;
    }

    @Override
    public Setting mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.key = input.readString();
            break;
          }
          case 18: {
            this.value = input.readString();
            break;
          }
        }
      }
    }

    public static Setting parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Setting(), data);
    }

    public static Setting parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Setting().mergeFrom(input);
    }
  }

  public static final class HeartBeatConfig extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HeartBeatConfig[] _emptyArray;
    public static HeartBeatConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HeartBeatConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 interval = 3;
    public long interval;

    // optional string ip = 2;
    public String ip;

    // optional bool uploadstat = 1;
    public boolean uploadstat;

    public HeartBeatConfig() {
      clear();
    }

    public HeartBeatConfig clear() {
      interval = 0L;
      ip = "";
      uploadstat = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uploadstat != false) {
        output.writeBool(1, this.uploadstat);
      }
      if (!this.ip.equals("")) {
        output.writeString(2, this.ip);
      }
      if (this.interval != 0L) {
        output.writeInt64(3, this.interval);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uploadstat != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.uploadstat);
      }
      if (!this.ip.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.ip);
      }
      if (this.interval != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.interval);
      }
      return size;
    }

    @Override
    public HeartBeatConfig mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uploadstat = input.readBool();
            break;
          }
          case 18: {
            this.ip = input.readString();
            break;
          }
          case 24: {
            this.interval = input.readInt64();
            break;
          }
        }
      }
    }

    public static HeartBeatConfig parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HeartBeatConfig(), data);
    }

    public static HeartBeatConfig parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HeartBeatConfig().mergeFrom(input);
    }
  }

  public static final class LoginResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LoginResponse[] _emptyArray;
    public static LoginResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LoginResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string packetid = 1;
    public String packetid;

    // optional string jid = 2;
    public String jid;

    // optional int64 servertimestamp = 8;
    public long servertimestamp;

    // optional .HeartBeatConfig heartbeatconfig = 7;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.HeartBeatConfig heartbeatconfig;

    // repeated .Setting settings = 4;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[] settings;

    // optional int32 laststreamid = 6;
    public int laststreamid;

    // optional int32 streamid = 5;
    public int streamid;

    // optional .XMPPError error = 3;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError error;

    public LoginResponse() {
      clear();
    }

    public LoginResponse clear() {
      packetid = "";
      jid = "";
      servertimestamp = 0L;
      heartbeatconfig = null;
      settings = com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting.emptyArray();
      laststreamid = 0;
      streamid = 0;
      error = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packetid.equals("")) {
        output.writeString(1, this.packetid);
      }
      if (!this.jid.equals("")) {
        output.writeString(2, this.jid);
      }
      if (this.error != null) {
        output.writeMessage(3, this.error);
      }
      if (this.settings != null && this.settings.length > 0) {
        for (int i = 0; i < this.settings.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting element = this.settings[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.streamid != 0) {
        output.writeInt32(5, this.streamid);
      }
      if (this.laststreamid != 0) {
        output.writeInt32(6, this.laststreamid);
      }
      if (this.heartbeatconfig != null) {
        output.writeMessage(7, this.heartbeatconfig);
      }
      if (this.servertimestamp != 0L) {
        output.writeInt64(8, this.servertimestamp);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packetid);
      }
      if (!this.jid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.jid);
      }
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.error);
      }
      if (this.settings != null && this.settings.length > 0) {
        for (int i = 0; i < this.settings.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting element = this.settings[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.streamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.streamid);
      }
      if (this.laststreamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.laststreamid);
      }
      if (this.heartbeatconfig != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.heartbeatconfig);
      }
      if (this.servertimestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.servertimestamp);
      }
      return size;
    }

    @Override
    public LoginResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packetid = input.readString();
            break;
          }
          case 18: {
            this.jid = input.readString();
            break;
          }
          case 26: {
            if (this.error == null) {
              this.error = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError();
            }
            input.readMessage(this.error);
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.settings == null ? 0 : this.settings.length;
              com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[] newArray =
                new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.settings, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Setting();
            input.readMessage(newArray[i]);
            this.settings = newArray;
            break;
          }
          case 40: {
            this.streamid = input.readInt32();
            break;
          }
          case 48: {
            this.laststreamid = input.readInt32();
            break;
          }
          case 58: {
            if (this.heartbeatconfig == null) {
              this.heartbeatconfig = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.HeartBeatConfig();
            }
            input.readMessage(this.heartbeatconfig);
            break;
          }
          case 64: {
            this.servertimestamp = input.readInt64();
            break;
          }
        }
      }
    }

    public static LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LoginResponse(), data);
    }

    public static LoginResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LoginResponse().mergeFrom(input);
    }
  }

  public static final class XMPPError extends
      com.google.protobuf.nano.MessageNano {

    private static volatile XMPPError[] _emptyArray;
    public static XMPPError[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new XMPPError[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 code = 1;
    public int code;

    // optional string message = 2;
    public String message;

    // optional string type = 3;
    public String type;

    // repeated .Extension extension = 4;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension[] extension;

    public XMPPError() {
      clear();
    }

    public XMPPError clear() {
      code = 0;
      message = "";
      type = "";
      extension = com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != 0) {
        output.writeInt32(1, this.code);
      }
      if (!this.message.equals("")) {
        output.writeString(2, this.message);
      }
      if (!this.type.equals("")) {
        output.writeString(3, this.type);
      }
      if (this.extension != null && this.extension.length > 0) {
        for (int i = 0; i < this.extension.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension element = this.extension[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.code);
      }
      if (!this.message.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.message);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.type);
      }
      if (this.extension != null && this.extension.length > 0) {
        for (int i = 0; i < this.extension.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension element = this.extension[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public XMPPError mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.code = input.readInt32();
            break;
          }
          case 18: {
            this.message = input.readString();
            break;
          }
          case 26: {
            this.type = input.readString();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.extension == null ? 0 : this.extension.length;
              com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension[] newArray =
                new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.extension, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension();
            input.readMessage(newArray[i]);
            this.extension = newArray;
            break;
          }
        }
      }
    }

    public static XMPPError parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new XMPPError(), data);
    }

    public static XMPPError parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new XMPPError().mergeFrom(input);
    }
  }

  public static final class Extension extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Extension[] _emptyArray;
    public static Extension[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Extension[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 code = 1;
    public int code;

    // optional string message = 2;
    public String message;

    public Extension() {
      clear();
    }

    public Extension clear() {
      code = 0;
      message = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != 0) {
        output.writeInt32(1, this.code);
      }
      if (!this.message.equals("")) {
        output.writeString(2, this.message);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.code);
      }
      if (!this.message.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.message);
      }
      return size;
    }

    @Override
    public Extension mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.code = input.readInt32();
            break;
          }
          case 18: {
            this.message = input.readString();
            break;
          }
        }
      }
    }

    public static Extension parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Extension(), data);
    }

    public static Extension parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Extension().mergeFrom(input);
    }
  }

  public static final class BindAccountRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BindAccountRequest[] _emptyArray;
    public static BindAccountRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BindAccountRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string packetid = 1;
    public String packetid;

    // optional string domain = 2;
    public String domain;

    // optional string user = 3;
    public String user;

    // optional string resource = 4;
    public String resource;

    // optional int64 accountid = 9;
    public long accountid;

    // optional string token = 5;
    public String token;

    public BindAccountRequest() {
      clear();
    }

    public BindAccountRequest clear() {
      packetid = "";
      domain = "";
      user = "";
      resource = "";
      accountid = 0L;
      token = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packetid.equals("")) {
        output.writeString(1, this.packetid);
      }
      if (!this.domain.equals("")) {
        output.writeString(2, this.domain);
      }
      if (!this.user.equals("")) {
        output.writeString(3, this.user);
      }
      if (!this.resource.equals("")) {
        output.writeString(4, this.resource);
      }
      if (!this.token.equals("")) {
        output.writeString(5, this.token);
      }
      if (this.accountid != 0L) {
        output.writeInt64(9, this.accountid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packetid);
      }
      if (!this.domain.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domain);
      }
      if (!this.user.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.user);
      }
      if (!this.resource.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.resource);
      }
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.token);
      }
      if (this.accountid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(9, this.accountid);
      }
      return size;
    }

    @Override
    public BindAccountRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packetid = input.readString();
            break;
          }
          case 18: {
            this.domain = input.readString();
            break;
          }
          case 26: {
            this.user = input.readString();
            break;
          }
          case 34: {
            this.resource = input.readString();
            break;
          }
          case 42: {
            this.token = input.readString();
            break;
          }
          case 72: {
            this.accountid = input.readInt64();
            break;
          }
        }
      }
    }

    public static BindAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BindAccountRequest(), data);
    }

    public static BindAccountRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BindAccountRequest().mergeFrom(input);
    }
  }

  public static final class BindAccountResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BindAccountResponse[] _emptyArray;
    public static BindAccountResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BindAccountResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string packetid = 1;
    public String packetid;

    // optional string jid = 2;
    public String jid;

    // optional int32 laststreamid = 5;
    public int laststreamid;

    // optional int32 streamid = 4;
    public int streamid;

    // optional .XMPPError error = 3;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError error;

    public BindAccountResponse() {
      clear();
    }

    public BindAccountResponse clear() {
      packetid = "";
      jid = "";
      laststreamid = 0;
      streamid = 0;
      error = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packetid.equals("")) {
        output.writeString(1, this.packetid);
      }
      if (!this.jid.equals("")) {
        output.writeString(2, this.jid);
      }
      if (this.error != null) {
        output.writeMessage(3, this.error);
      }
      if (this.streamid != 0) {
        output.writeInt32(4, this.streamid);
      }
      if (this.laststreamid != 0) {
        output.writeInt32(5, this.laststreamid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packetid);
      }
      if (!this.jid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.jid);
      }
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.error);
      }
      if (this.streamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.streamid);
      }
      if (this.laststreamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.laststreamid);
      }
      return size;
    }

    @Override
    public BindAccountResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packetid = input.readString();
            break;
          }
          case 18: {
            this.jid = input.readString();
            break;
          }
          case 26: {
            if (this.error == null) {
              this.error = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError();
            }
            input.readMessage(this.error);
            break;
          }
          case 32: {
            this.streamid = input.readInt32();
            break;
          }
          case 40: {
            this.laststreamid = input.readInt32();
            break;
          }
        }
      }
    }

    public static BindAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BindAccountResponse(), data);
    }

    public static BindAccountResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BindAccountResponse().mergeFrom(input);
    }
  }

  public static final class Close extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Close[] _emptyArray;
    public static Close[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Close[0];
          }
        }
      }
      return _emptyArray;
    }

    public Close() {
      clear();
    }

    public Close clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public Close mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static Close parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Close(), data);
    }

    public static Close parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Close().mergeFrom(input);
    }
  }

  public static final class HeartbeatAck extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HeartbeatAck[] _emptyArray;
    public static HeartbeatAck[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HeartbeatAck[0];
          }
        }
      }
      return _emptyArray;
    }

    public HeartbeatAck() {
      clear();
    }

    public HeartbeatAck clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public HeartbeatAck mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static HeartbeatAck parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HeartbeatAck(), data);
    }

    public static HeartbeatAck parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HeartbeatAck().mergeFrom(input);
    }
  }

  public static final class DataMessageStanza extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DataMessageStanza[] _emptyArray;
    public static DataMessageStanza[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DataMessageStanza[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 rmqid = 1;
    public long rmqid;

    // optional string packetid = 2;
    public String packetid;

    // optional string from = 3;
    public String from;

    // optional string to = 4;
    public String to;

    // optional string category = 5;
    public String category;

    // optional string token = 6;
    public String token;

    // repeated .AppData appdata = 7;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData[] appdata;

    // optional bool fromtrustedserver = 8;
    public boolean fromtrustedserver;

    // optional string rmq2id = 9;
    public String rmq2Id;

    // optional int32 streamid = 10;
    public int streamid;

    // optional int32 laststreamid = 11;
    public int laststreamid;

    // optional string permission = 12;
    public String permission;

    // optional string regid = 13;
    public String regid;

    // optional string pkgsignature = 14;
    public String pkgsignature;

    public DataMessageStanza() {
      clear();
    }

    public DataMessageStanza clear() {
      rmqid = 0L;
      packetid = "";
      from = "";
      to = "";
      category = "";
      token = "";
      appdata = com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData.emptyArray();
      fromtrustedserver = false;
      rmq2Id = "";
      streamid = 0;
      laststreamid = 0;
      permission = "";
      regid = "";
      pkgsignature = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rmqid != 0L) {
        output.writeInt64(1, this.rmqid);
      }
      if (!this.packetid.equals("")) {
        output.writeString(2, this.packetid);
      }
      if (!this.from.equals("")) {
        output.writeString(3, this.from);
      }
      if (!this.to.equals("")) {
        output.writeString(4, this.to);
      }
      if (!this.category.equals("")) {
        output.writeString(5, this.category);
      }
      if (!this.token.equals("")) {
        output.writeString(6, this.token);
      }
      if (this.appdata != null && this.appdata.length > 0) {
        for (int i = 0; i < this.appdata.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData element = this.appdata[i];
          if (element != null) {
            output.writeMessage(7, element);
          }
        }
      }
      if (this.fromtrustedserver != false) {
        output.writeBool(8, this.fromtrustedserver);
      }
      if (!this.rmq2Id.equals("")) {
        output.writeString(9, this.rmq2Id);
      }
      if (this.streamid != 0) {
        output.writeInt32(10, this.streamid);
      }
      if (this.laststreamid != 0) {
        output.writeInt32(11, this.laststreamid);
      }
      if (!this.permission.equals("")) {
        output.writeString(12, this.permission);
      }
      if (!this.regid.equals("")) {
        output.writeString(13, this.regid);
      }
      if (!this.pkgsignature.equals("")) {
        output.writeString(14, this.pkgsignature);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rmqid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.rmqid);
      }
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.packetid);
      }
      if (!this.from.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.from);
      }
      if (!this.to.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.to);
      }
      if (!this.category.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.category);
      }
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.token);
      }
      if (this.appdata != null && this.appdata.length > 0) {
        for (int i = 0; i < this.appdata.length; i++) {
            com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData element = this.appdata[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(7, element);
          }
        }
      }
      if (this.fromtrustedserver != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.fromtrustedserver);
      }
      if (!this.rmq2Id.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.rmq2Id);
      }
      if (this.streamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.streamid);
      }
      if (this.laststreamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(11, this.laststreamid);
      }
      if (!this.permission.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.permission);
      }
      if (!this.regid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.regid);
      }
      if (!this.pkgsignature.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.pkgsignature);
      }
      return size;
    }

    @Override
    public DataMessageStanza mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rmqid = input.readInt64();
            break;
          }
          case 18: {
            this.packetid = input.readString();
            break;
          }
          case 26: {
            this.from = input.readString();
            break;
          }
          case 34: {
            this.to = input.readString();
            break;
          }
          case 42: {
            this.category = input.readString();
            break;
          }
          case 50: {
            this.token = input.readString();
            break;
          }
          case 58: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 58);
            int i = this.appdata == null ? 0 : this.appdata.length;
              com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData[] newArray =
                new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.appdata, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.AppData();
            input.readMessage(newArray[i]);
            this.appdata = newArray;
            break;
          }
          case 64: {
            this.fromtrustedserver = input.readBool();
            break;
          }
          case 74: {
            this.rmq2Id = input.readString();
            break;
          }
          case 80: {
            this.streamid = input.readInt32();
            break;
          }
          case 88: {
            this.laststreamid = input.readInt32();
            break;
          }
          case 98: {
            this.permission = input.readString();
            break;
          }
          case 106: {
            this.regid = input.readString();
            break;
          }
          case 114: {
            this.pkgsignature = input.readString();
            break;
          }
        }
      }
    }

    public static DataMessageStanza parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DataMessageStanza(), data);
    }

    public static DataMessageStanza parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DataMessageStanza().mergeFrom(input);
    }
  }

  public static final class AppData extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AppData[] _emptyArray;
    public static AppData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AppData[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string key = 1;
    public String key;

    // optional string value = 2;
    public String value;

    public AppData() {
      clear();
    }

    public AppData clear() {
      key = "";
      value = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.key.equals("")) {
        output.writeString(1, this.key);
      }
      if (!this.value.equals("")) {
        output.writeString(2, this.value);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.key.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.key);
      }
      if (!this.value.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.value);
      }
      return size;
    }

    @Override
    public AppData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.key = input.readString();
            break;
          }
          case 18: {
            this.value = input.readString();
            break;
          }
        }
      }
    }

    public static AppData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AppData(), data);
    }

    public static AppData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AppData().mergeFrom(input);
    }
  }

  public static final class IQStanza extends
      com.google.protobuf.nano.MessageNano {

    private static volatile IQStanza[] _emptyArray;
    public static IQStanza[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new IQStanza[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 rmqid = 1;
    public long rmqid;

    // optional int32 type = 2;
    public int type;

    // optional string packetid = 3;
    public String packetid;

    // optional string from = 4;
    public String from;

    // optional string to = 5;
    public String to;

    // optional .XMPPError error = 6;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError error;

    // optional .Extension extension = 7;
    public com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension extension;

    // optional string rmq2id = 8;
    public String rmq2Id;

    // optional int32 streamid = 9;
    public int streamid;

    // optional int32 laststreamid = 10;
    public int laststreamid;

    // optional int64 accountid = 11;
    public long accountid;

    public IQStanza() {
      clear();
    }

    public IQStanza clear() {
      rmqid = 0L;
      type = 0;
      packetid = "";
      from = "";
      to = "";
      error = null;
      extension = null;
      rmq2Id = "";
      streamid = 0;
      laststreamid = 0;
      accountid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rmqid != 0L) {
        output.writeInt64(1, this.rmqid);
      }
      if (this.type != 0) {
        output.writeInt32(2, this.type);
      }
      if (!this.packetid.equals("")) {
        output.writeString(3, this.packetid);
      }
      if (!this.from.equals("")) {
        output.writeString(4, this.from);
      }
      if (!this.to.equals("")) {
        output.writeString(5, this.to);
      }
      if (this.error != null) {
        output.writeMessage(6, this.error);
      }
      if (this.extension != null) {
        output.writeMessage(7, this.extension);
      }
      if (!this.rmq2Id.equals("")) {
        output.writeString(8, this.rmq2Id);
      }
      if (this.streamid != 0) {
        output.writeInt32(9, this.streamid);
      }
      if (this.laststreamid != 0) {
        output.writeInt32(10, this.laststreamid);
      }
      if (this.accountid != 0L) {
        output.writeInt64(11, this.accountid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rmqid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.rmqid);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.type);
      }
      if (!this.packetid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.packetid);
      }
      if (!this.from.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.from);
      }
      if (!this.to.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.to);
      }
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.error);
      }
      if (this.extension != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.extension);
      }
      if (!this.rmq2Id.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.rmq2Id);
      }
      if (this.streamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.streamid);
      }
      if (this.laststreamid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.laststreamid);
      }
      if (this.accountid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(11, this.accountid);
      }
      return size;
    }

    @Override
    public IQStanza mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rmqid = input.readInt64();
            break;
          }
          case 16: {
            this.type = input.readInt32();
            break;
          }
          case 26: {
            this.packetid = input.readString();
            break;
          }
          case 34: {
            this.from = input.readString();
            break;
          }
          case 42: {
            this.to = input.readString();
            break;
          }
          case 50: {
            if (this.error == null) {
              this.error = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.XMPPError();
            }
            input.readMessage(this.error);
            break;
          }
          case 58: {
            if (this.extension == null) {
              this.extension = new com.testappnongpdownload.app.playstoreapiutils.GoogleServicesFramework.Extension();
            }
            input.readMessage(this.extension);
            break;
          }
          case 66: {
            this.rmq2Id = input.readString();
            break;
          }
          case 72: {
            this.streamid = input.readInt32();
            break;
          }
          case 80: {
            this.laststreamid = input.readInt32();
            break;
          }
          case 88: {
            this.accountid = input.readInt64();
            break;
          }
        }
      }
    }

    public static IQStanza parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new IQStanza(), data);
    }

    public static IQStanza parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new IQStanza().mergeFrom(input);
    }
  }

  public static final class State extends
      com.google.protobuf.nano.MessageNano {

    private static volatile State[] _emptyArray;
    public static State[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new State[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool state1 = 1;
    public boolean state1;

    // optional bool state2 = 2;
    public boolean state2;

    public State() {
      clear();
    }

    public State clear() {
      state1 = false;
      state2 = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.state1 != false) {
        output.writeBool(1, this.state1);
      }
      if (this.state2 != false) {
        output.writeBool(2, this.state2);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.state1 != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.state1);
      }
      if (this.state2 != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.state2);
      }
      return size;
    }

    @Override
    public State mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.state1 = input.readBool();
            break;
          }
          case 16: {
            this.state2 = input.readBool();
            break;
          }
        }
      }
    }

    public static State parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new State(), data);
    }

    public static State parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new State().mergeFrom(input);
    }
  }

  public static final class PostAuthBatchQuery extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PostAuthBatchQuery[] _emptyArray;
    public static PostAuthBatchQuery[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PostAuthBatchQuery[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool online = 1;
    public boolean online;

    // optional bool deviceidle = 2;
    public boolean deviceidle;

    // optional bool showmobileindicator = 3;
    public boolean showmobileindicator;

    // optional int32 sharedstatusversion = 4;
    public int sharedstatusversion;

    // optional string rosteretag = 5;
    public String rosteretag;

    // optional string otretag = 6;
    public String otretag;

    // optional string avatarhash = 7;
    public String avatarhash;

    // optional string vcardquerystanzaid = 8;
    public String vcardquerystanzaid;

    // optional int32 capabilities = 9;
    public int capabilities;

    public PostAuthBatchQuery() {
      clear();
    }

    public PostAuthBatchQuery clear() {
      online = false;
      deviceidle = false;
      showmobileindicator = false;
      sharedstatusversion = 0;
      rosteretag = "";
      otretag = "";
      avatarhash = "";
      vcardquerystanzaid = "";
      capabilities = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.online != false) {
        output.writeBool(1, this.online);
      }
      if (this.deviceidle != false) {
        output.writeBool(2, this.deviceidle);
      }
      if (this.showmobileindicator != false) {
        output.writeBool(3, this.showmobileindicator);
      }
      if (this.sharedstatusversion != 0) {
        output.writeInt32(4, this.sharedstatusversion);
      }
      if (!this.rosteretag.equals("")) {
        output.writeString(5, this.rosteretag);
      }
      if (!this.otretag.equals("")) {
        output.writeString(6, this.otretag);
      }
      if (!this.avatarhash.equals("")) {
        output.writeString(7, this.avatarhash);
      }
      if (!this.vcardquerystanzaid.equals("")) {
        output.writeString(8, this.vcardquerystanzaid);
      }
      if (this.capabilities != 0) {
        output.writeInt32(9, this.capabilities);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.online != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.online);
      }
      if (this.deviceidle != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.deviceidle);
      }
      if (this.showmobileindicator != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, this.showmobileindicator);
      }
      if (this.sharedstatusversion != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.sharedstatusversion);
      }
      if (!this.rosteretag.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.rosteretag);
      }
      if (!this.otretag.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.otretag);
      }
      if (!this.avatarhash.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.avatarhash);
      }
      if (!this.vcardquerystanzaid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.vcardquerystanzaid);
      }
      if (this.capabilities != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.capabilities);
      }
      return size;
    }

    @Override
    public PostAuthBatchQuery mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.online = input.readBool();
            break;
          }
          case 16: {
            this.deviceidle = input.readBool();
            break;
          }
          case 24: {
            this.showmobileindicator = input.readBool();
            break;
          }
          case 32: {
            this.sharedstatusversion = input.readInt32();
            break;
          }
          case 42: {
            this.rosteretag = input.readString();
            break;
          }
          case 50: {
            this.otretag = input.readString();
            break;
          }
          case 58: {
            this.avatarhash = input.readString();
            break;
          }
          case 66: {
            this.vcardquerystanzaid = input.readString();
            break;
          }
          case 72: {
            this.capabilities = input.readInt32();
            break;
          }
        }
      }
    }

    public static PostAuthBatchQuery parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PostAuthBatchQuery(), data);
    }

    public static PostAuthBatchQuery parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PostAuthBatchQuery().mergeFrom(input);
    }
  }
}
